function footer() {

document.write(
	'<footer id="colophon" class="site-footer"><div class="footer-head-wrap animated invisible" data-animate="fadeInUp">',
	'        <a href="/" rel="home" class="footer-logo pos-ab-c"></a>',
	'    </div>',
	'    <div class="footer-nav-wrap">',
	'    <ul class="footer-nav">',
	'<li class="navpick-rpa menu-item menu-item-type-post_type menu-item-object-page menu-item-99"><a href="/rpainfo/">取扱商品紹介</a></li>',
	'<li class="navpick-support menu-item menu-item-type-post_type menu-item-object-page menu-item-100"><a href="https://forms.office.com/r/XypstJFU8R">お問い合わせ</a></li>',
	'     </ul>',
	'<ul class="footer-nav">',
	'<li id="menu-item-101" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-101"><a href="/about/">企業情報</a></li>',
	'<li id="menu-item-105" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-105"><a href="/about/outline/">会社概要</a></li>',
	'<li id="menu-item-107" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-107"><a href="/about/principle/">企業方針</a></li>',
	'<li id="menu-item-103" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-103"><a href="/about/history/">沿革</a></li>',
	'<li id="menu-item-102" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-102"><a href="/about/access/">アクセス</a></li>',
	'     </ul>',
	'<ul class="footer-nav">',
	'<li id="menu-item-680" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-680"><a href="/about/lduinfo/">公開情報</a></li>',
	'<li id="menu-item-679" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-privacy-policy menu-item-679"><a href="/about/privacy/">プライバシーポリシー</a></li>',
	'     </ul>',
	'<ul class="footer-nav">',
	'<li id="menu-item-487" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-487"><a href="/techinfo/">技術情報</a></li>',
	'<li id="menu-item-484" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-484"><a href="/techinfo/ee-division/">組込みエンジニアリング</a></li>',
	'<li id="menu-item-687" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-687"><a href="/techinfo/ss-division/">S.I.ソリューション</a></li>',
	'<li id="menu-item-686" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-686"><a href="/techinfo/ps-division/">プロダクトソリューション</a></li>',
	'     </ul>',
	'<ul class="footer-nav footer-nav-bottom">',
	'<li id="menu-item-684" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-684"><a href="/csr/">社会貢献</a></li>',
	'<li id="menu-item-685" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-685"><a href="/csr/environment/">環境方針</a></li>',
	'<li id="menu-item-1154" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1154"><a href="/csr/sdgs/">SDGs</a></li>',
	'<li id="menu-item-688" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-688"><a href="/recruit/">採用情報</a></li>',
	'     </ul>',
	'<ul class="sns-link">',
	'<li><a style="width: 60px;" href="https://twitter.com/_M_M_I_" target="_blank"><i class="fab fa-twitter"></i></a></li>',
	'    <li><a style="width: 60px;" href="https://www.facebook.com/%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE%E3%83%9E%E3%83%B3%E3%83%9E%E3%82%B7%E3%83%B3%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%95%E3%82%A7%E3%83%BC%E3%82%B9-503152396497579/" target="_blank"><i class="fab fa-facebook-square"></i></a></li>',
	'          </ul>',
	'</div>',
	'    <div class="site-info">',
	'        <small>&copy; <span id="thisYear"></span> MAN MACHINE INTERFACE,INC.</small>',
	'    </div>',
	'    <!-- .site-info -->',
	'</footer>',
	'</div>',
	'<!-- #page -->'
);

}
